---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: crccheck/hello-world
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1100m
              memory: 500Mi
          ports:
            - containerPort: 8000
